<a href="https://colab.research.google.com/github/yananma/5_programs_per_day/blob/master/04202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 4.6 GPU 计算

In [1]:
!nvidia-smi

Wed Dec 11 17:56:46 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.36       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   72C    P8    35W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

### 4.6.1 计算设备

In [2]:
import torch 
from torch import nn 

torch.cuda.is_available()

True

In [3]:
torch.cuda.device_count()

1

In [4]:
torch.cuda.current_device()

0

In [5]:
torch.cuda.get_device_name(0)

'Tesla K80'

### 4.6.2 Tensor 的 GPU 计算

In [6]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [7]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [8]:
x.device

device(type='cuda', index=0)

In [10]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

In [11]:
y = x**2 
y

tensor([1, 4, 9], device='cuda:0')

In [12]:
z = y + x.cpu()

RuntimeError: ignored

### 4.6.3 模型的 GPU 计算

In [13]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [14]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [15]:
x = torch.rand(2, 3).cuda()
net(x)

tensor([[-0.0766],
        [-0.0008]], device='cuda:0', grad_fn=<AddmmBackward>)