<a href="https://colab.research.google.com/github/yananma/5_programs_per_day/blob/master/0426.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 2.2 数据操作

### 2.2.1 创建 Tensor

In [0]:
import torch

In [64]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
x.shape

torch.Size([12])

In [66]:
x.size()

torch.Size([12])

In [67]:
X = x.view(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [68]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [69]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [70]:
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [71]:
torch.randn(3, 4)

tensor([[ 0.2891,  1.4772,  1.1930, -0.2594],
        [ 0.5542,  1.1555, -0.6077, -0.5736],
        [-0.5151, -0.8062,  0.0393, -0.1459]])

### 2.2.2 运算

In [72]:
X + Y

tensor([[ 2,  2,  6,  6],
        [ 5,  7,  9, 11],
        [12, 12, 12, 12]])

In [73]:
X * Y

tensor([[ 0,  1,  8,  9],
        [ 4, 10, 18, 28],
        [32, 27, 20, 11]])

In [74]:
torch.div(X, Y)

tensor([[ 0,  1,  0,  1],
        [ 4,  2,  2,  1],
        [ 2,  3,  5, 11]])

In [75]:
X / Y

tensor([[ 0,  1,  0,  1],
        [ 4,  2,  2,  1],
        [ 2,  3,  5, 11]])

In [76]:
torch.exp(Y.float())

tensor([[ 7.3891,  2.7183, 54.5981, 20.0855],
        [ 2.7183,  7.3891, 20.0855, 54.5981],
        [54.5981, 20.0855,  7.3891,  2.7183]])

In [77]:
torch.mm(X, Y.T)

tensor([[ 18,  20,  10],
        [ 58,  60,  50],
        [ 98, 100,  90]])

In [78]:
torch.cat((X, Y), 0)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])

In [79]:
torch.cat((X, Y), 1)

tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])

In [80]:
(X == Y).int()

tensor([[0, 1, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [81]:
X.sum()

tensor(66)

In [82]:
X.float().norm().item()

22.494443893432617

### 2.2.3 广播机制

In [83]:
A = torch.arange(3).view(3, 1)
B = torch.arange(2).view(1, 2)
A, B

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

In [84]:
A + B

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.2.4 索引

In [85]:
X[1:3]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [86]:
X[1, 2] = 9
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

In [87]:
X[1:2, :] = 12 
X

tensor([[ 0,  1,  2,  3],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

### 2.2.5 运算的内存开销

In [88]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [89]:
Z = torch.zeros_like(Y)
before = id(Z)
Z[:] = X + Y 
id(Z) == before

True

In [90]:
torch.add(X, Y, out=Z)
id(Z) == before

True

In [91]:
before = id(X)
X += Y 
id(X) == before

True

### 2.2.6 Tensor 和 NumPy 互相转换

In [92]:
import numpy as np 

P = np.ones((2, 3))
T = torch.from_numpy(P)
T

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [93]:
T.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]])