<a href="https://colab.research.google.com/github/yananma/5_programs_per_day/blob/master/0506.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 2.2 数据操作

In [0]:
!pip install mxnet d2lzh 

In [0]:
from mxnet import nd 

In [3]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [4]:
x.shape

(12,)

In [5]:
x.size 

12

In [6]:
X = x.reshape((3, 4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [7]:
nd.zeros((2, 3, 4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [8]:
nd.ones((3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [9]:
Y = nd.array([[2, 1, 3, 4], [1, 2, 3, 4], [4, 3, 2, 1]])
Y


[[2. 1. 3. 4.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [11]:
nd.random.normal(0, 1, shape=(3, 4))


[[ 2.2122064   0.7740038   1.0434403   1.1839255 ]
 [ 1.8917114  -1.2347414  -1.771029   -0.45138445]
 [ 0.57938355 -1.856082   -1.9768796  -0.20801921]]
<NDArray 3x4 @cpu(0)>

In [12]:
X + Y 


[[ 2.  2.  5.  7.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [13]:
X * Y 


[[ 0.  1.  6. 12.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [14]:
X / Y 


[[ 0.         1.         0.6666667  0.75     ]
 [ 4.         2.5        2.         1.75     ]
 [ 2.         3.         5.        11.       ]]
<NDArray 3x4 @cpu(0)>

In [15]:
Y.exp()


[[ 7.389056   2.7182817 20.085537  54.59815  ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

In [16]:
nd.dot(X, Y.T)


[[ 19.  20.  10.]
 [ 59.  60.  50.]
 [ 99. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [18]:
nd.concat(X, Y, dim=0)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  3.  4.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>

In [19]:
nd.concat(X, Y, dim=1)


[[ 0.  1.  2.  3.  2.  1.  3.  4.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>

In [0]:
X = nd.arange(12).reshape((3, 4))

In [23]:
X == Y 


[[0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [24]:
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [25]:
X.sum()


[66.]
<NDArray 1 @cpu(0)>

In [26]:
X.norm().asscalar()

22.494442

In [27]:
A = nd.arange(3).reshape((3, 1))
B = nd.arange(2).reshape((1, 2))
A


[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>

In [28]:
B


[[0. 1.]]
<NDArray 1x2 @cpu(0)>

In [29]:
A + B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [30]:
X[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [31]:
X[1, 2]
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [32]:
X[1:2, :] = 12 
X 


[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [33]:
before = id(Y)
Y = Y + X 
id(Y) == before 

False

In [36]:
Z = Y.zeros_like()
before = id(Z)
Z[:] = X + Y 
id(Z) == before 

True

In [37]:
before  = id(X)
X += Y 
id(X) == before 

True

In [39]:
import numpy as np 

P = np.ones((2, 3))
D = nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [40]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

## 2.3 自动求梯度

In [0]:
from mxnet import autograd, nd 

In [42]:
x = nd.arange(4).reshape((4, 1))
x 


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [0]:
x.attach_grad()

In [0]:
with autograd.record():
    y = 2 * nd.dot(x.T, x)

In [0]:
y.backward()

In [46]:
assert (x.grad - 4 * x).norm().asscalar() == 0 
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [47]:
print(autograd.is_training())
with autograd.record():
    print(autograd.is_training())

False
True


In [0]:
def f(a):
    b = a * 2 
    print('b1:', b)
    n = 0 
    while b.norm().asscalar() < 1000:
        n += 1 
        b = b * 2
    print('n:', n) 
    print('b2:', b)
    if b.sum().asscalar() > 0:
        c = b 
        print('c1:', c)
    else:
        c = 100 * b 
        print('c2:', c)
    return c 

In [87]:
a = nd.random.normal(shape=(3, 4))
print(a)
a.attach_grad()
with autograd.record():
    c = f(a)
c.backward()


[[-1.88909     0.65479124 -0.45481315  0.32510808]
 [-1.3002341   0.3679345   1.4534262   0.24154152]
 [ 0.47898006  0.96885103 -1.0218245  -0.06812762]]
<NDArray 3x4 @cpu(0)>
b1: 
[[-3.77818     1.3095825  -0.9096263   0.65021616]
 [-2.6004682   0.735869    2.9068525   0.48308304]
 [ 0.9579601   1.9377021  -2.043649   -0.13625523]]
<NDArray 3x4 @cpu(0)>
n: 8
b2: 
[[-967.21405  335.2531  -232.86433  166.45534]
 [-665.71985  188.38246  744.15424  123.66926]
 [ 245.2378   496.05173 -523.17413  -34.88134]]
<NDArray 3x4 @cpu(0)>
c2: 
[[-96721.41   33525.312 -23286.434  16645.533]
 [-66571.984  18838.246  74415.42   12366.926]
 [ 24523.78   49605.17  -52317.414  -3488.134]]
<NDArray 3x4 @cpu(0)>


In [88]:
a.grad == c / a 


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [89]:
a.grad 


[[51200. 51200. 51200. 51200.]
 [51200. 51200. 51200. 51200.]
 [51200. 51200. 51200. 51200.]]
<NDArray 3x4 @cpu(0)>

# PyTorch 

## 2.2 数据操作

In [0]:
import torch 

In [112]:
x = torch.empty(5, 3)
print(x)

tensor([[2.2906e-34, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 5.1208e-01],
        [1.3554e-05, 3.4152e-06, 1.3090e+22],
        [2.1876e-04, 8.2290e-10, 4.1729e+21],
        [4.2007e-05, 5.3772e+22, 1.3368e+00]])


In [113]:
x

tensor([[2.2906e-34, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 5.1208e-01],
        [1.3554e-05, 3.4152e-06, 1.3090e+22],
        [2.1876e-04, 8.2290e-10, 4.1729e+21],
        [4.2007e-05, 5.3772e+22, 1.3368e+00]])

In [114]:
x = torch.rand(5, 3)
x

tensor([[0.9742, 0.3791, 0.2096],
        [0.6549, 0.2182, 0.4989],
        [0.2401, 0.9136, 0.3931],
        [0.6601, 0.3845, 0.5110],
        [0.5142, 0.8150, 0.4168]])

In [0]:
# torch.rand??

In [116]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [117]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [118]:
x = x.new_ones(5, 3, dtype=torch.float64)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [119]:
x = torch.randn_like(x, dtype=torch.float)
x 

tensor([[-0.3382,  1.0064,  1.3071],
        [-1.1685, -1.0985, -0.7131],
        [-1.5762,  1.0393, -0.2857],
        [ 0.2230, -0.4475, -0.0058],
        [ 0.8169,  0.2681, -0.8816]])

In [0]:
# torch.randn_like??

In [0]:
# for item in dir(torch.nn):
#     print(item)

In [122]:
x.size()

torch.Size([5, 3])

In [123]:
print(x.size())

torch.Size([5, 3])


In [124]:
print(x.size)

<built-in method size of Tensor object at 0x7fd36084b1b0>


In [125]:
print(x.shape)

torch.Size([5, 3])


In [127]:
print(x.shape)

torch.Size([5, 3])


In [128]:
x

tensor([[-0.3382,  1.0064,  1.3071],
        [-1.1685, -1.0985, -0.7131],
        [-1.5762,  1.0393, -0.2857],
        [ 0.2230, -0.4475, -0.0058],
        [ 0.8169,  0.2681, -0.8816]])

In [129]:
y = torch.rand(5, 3)
x + y 

tensor([[ 0.4636,  1.4516,  1.6162],
        [-0.2766, -0.4191, -0.0724],
        [-1.1186,  1.2172, -0.0934],
        [ 1.1718,  0.4459, -0.0020],
        [ 1.3284,  0.6314, -0.0286]])

In [130]:
torch.add(x, y)

tensor([[ 0.4636,  1.4516,  1.6162],
        [-0.2766, -0.4191, -0.0724],
        [-1.1186,  1.2172, -0.0934],
        [ 1.1718,  0.4459, -0.0020],
        [ 1.3284,  0.6314, -0.0286]])

In [131]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[ 0.4636,  1.4516,  1.6162],
        [-0.2766, -0.4191, -0.0724],
        [-1.1186,  1.2172, -0.0934],
        [ 1.1718,  0.4459, -0.0020],
        [ 1.3284,  0.6314, -0.0286]])

In [0]:
# torch.empty??

In [135]:
torch.empty(2, 3)

tensor([[2.2908e-34, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 6.4460e-44]])

In [136]:
y.add_(x)
y

tensor([[ 0.4636,  1.4516,  1.6162],
        [-0.2766, -0.4191, -0.0724],
        [-1.1186,  1.2172, -0.0934],
        [ 1.1718,  0.4459, -0.0020],
        [ 1.3284,  0.6314, -0.0286]])

In [137]:
y = x[0, :]
print(y)
y += 1 
print(y)
print(x[0, :])

tensor([-0.3382,  1.0064,  1.3071])
tensor([0.6618, 2.0064, 2.3071])
tensor([0.6618, 2.0064, 2.3071])


In [138]:
x 

tensor([[ 0.6618,  2.0064,  2.3071],
        [-1.1685, -1.0985, -0.7131],
        [-1.5762,  1.0393, -0.2857],
        [ 0.2230, -0.4475, -0.0058],
        [ 0.8169,  0.2681, -0.8816]])

In [139]:
y = x.view(15)
print(y)

tensor([ 0.6618,  2.0064,  2.3071, -1.1685, -1.0985, -0.7131, -1.5762,  1.0393,
        -0.2857,  0.2230, -0.4475, -0.0058,  0.8169,  0.2681, -0.8816])


In [140]:
print(y.size())

torch.Size([15])


In [141]:
z = x.view(-1, 5)
print(z)

tensor([[ 0.6618,  2.0064,  2.3071, -1.1685, -1.0985],
        [-0.7131, -1.5762,  1.0393, -0.2857,  0.2230],
        [-0.4475, -0.0058,  0.8169,  0.2681, -0.8816]])


In [142]:
x += 1 
print(x)

tensor([[ 1.6618,  3.0064,  3.3071],
        [-0.1685, -0.0985,  0.2869],
        [-0.5762,  2.0393,  0.7143],
        [ 1.2230,  0.5525,  0.9942],
        [ 1.8169,  1.2681,  0.1184]])


In [143]:
print(y)

tensor([ 1.6618,  3.0064,  3.3071, -0.1685, -0.0985,  0.2869, -0.5762,  2.0393,
         0.7143,  1.2230,  0.5525,  0.9942,  1.8169,  1.2681,  0.1184])


In [0]:
# x.view??

In [148]:
X = torch.arange(12).view(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [149]:
x_cp = x.clone().view(15)
x -= 1 
print(x)

tensor([[ 0.6618,  2.0064,  2.3071],
        [-1.1685, -1.0985, -0.7131],
        [-1.5762,  1.0393, -0.2857],
        [ 0.2230, -0.4475, -0.0058],
        [ 0.8169,  0.2681, -0.8816]])


In [150]:
print(x_cp)

tensor([ 1.6618,  3.0064,  3.3071, -0.1685, -0.0985,  0.2869, -0.5762,  2.0393,
         0.7143,  1.2230,  0.5525,  0.9942,  1.8169,  1.2681,  0.1184])


In [151]:
x = torch.randn(1)
x

tensor([-0.3648])

In [152]:
x.item()

-0.36481809616088867

In [0]:
# x.item??

In [0]:
my_x = nd.arange(12).reshape((3, 4))

In [157]:
my_x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [160]:
my_x.sum().asscalar()

66.0

In [0]:
A = torch.arange(3).view(3, 1)
B = torch.arange(2).view(1, 2)

In [162]:
A

tensor([[0],
        [1],
        [2]])

In [163]:
B

tensor([[0, 1]])

In [164]:
A + B

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [0]:
X = torch.tensor([1, 2])
Y = torch.tensor([3, 4])

In [167]:
before = id(Y)
Y = Y + X 
id(Y) == before

False

In [0]:
for item in dir(Y):
    print(item)

In [171]:
before = id(Y)
Y[:] = Y + X 
id(Y) == before

True

In [174]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
before = id(y)
torch.add(x, y, out=y)
id(y) == before

True

In [176]:
print(torch.cuda.is_available())

True


In [178]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y 
    print(z)

tensor([2, 3], device='cuda:0')


In [180]:
import numpy as np 

P = np.ones((2, 3))
# T = torch.tensor(P)
T = torch.from_numpy(P)
T

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [181]:
T.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]])