<a href="https://colab.research.google.com/github/yananma/5_programs_per_day/blob/master/1022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1、Basics

In [0]:
import torch 
import torch.nn as nn 
import torchvision 
import torchvision.transforms as transforms 
import numpy as np 

In [0]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

In [0]:
y = w * x + b

In [0]:
y.backward()

In [5]:
print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


In [0]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)

In [7]:
print(x)

tensor([[ 1.0312, -2.2192, -0.6348],
        [-1.5189,  0.3702,  0.9602],
        [ 0.1898,  0.3289, -0.0811],
        [-2.5768,  0.7972, -0.9014],
        [ 0.0455,  0.3736,  1.9475],
        [ 0.7540,  0.8177, -1.4106],
        [-0.3222,  1.7772, -0.5625],
        [-0.5454,  0.1586, -0.7365],
        [ 1.0256, -2.4679, -0.8952],
        [ 0.8316,  0.5770, -0.3232]])


In [12]:
linear = nn.Linear(3, 2)
print(linear.weight)

Parameter containing:
tensor([[-0.2948,  0.1837,  0.0578],
        [ 0.3154, -0.4837,  0.1353]], requires_grad=True)


In [16]:
print(linear.weight.size())

torch.Size([2, 3])


In [17]:
print(linear.weight.size(1))

3


In [18]:
print(linear.bias)

Parameter containing:
tensor([ 0.1048, -0.1609], requires_grad=True)


In [0]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

In [0]:
pred = linear(x)
loss = criterion(pred, y)

In [21]:
!pip install mxnet

     |████████████████████████████████| 25.4MB 1.2MB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1


In [0]:
from mxnet import nd 

In [0]:
x = nd.arange(12)

In [24]:
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [25]:
x.shape

(12,)

In [26]:
x.size

12

In [0]:
X = x.reshape((3, 4))

In [28]:
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [29]:
nd.zeros((2, 3, 4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [30]:
nd.ones((3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [31]:
Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [33]:
nd.random.normal(10, 1, shape=(3, 4))


[[10.244422  9.962839  9.51225   9.977383]
 [10.574615 11.466126 10.686291 10.354961]
 [11.07317  10.120174  9.02889   9.224303]]
<NDArray 3x4 @cpu(0)>

In [35]:
X + Y


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [36]:
X * Y


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [37]:
X / Y


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [39]:
Y.exp()


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

In [40]:
nd.dot(X, Y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [42]:
nd.concat(X, Y, dim=0)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>

In [43]:
nd.concat(X, Y, dim=1)


[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>

In [44]:
X == Y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [45]:
X.sum()


[66.]
<NDArray 1 @cpu(0)>

In [46]:
X.norm().asscalar()

22.494442

In [47]:
A = nd.arange(3).reshape((3, 1))
B = nd.arange(2).reshape((1, 2))
A, B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [48]:
A + B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [51]:
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [52]:
X[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [53]:
X[1, 2] = 9
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [55]:
X[1:2, :] = 12 
X


[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [56]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [61]:
Z = Y.zeros_like()
before = id(Z)
Z[:] = X + Y 
id(Z) == before

True

In [62]:
nd.elemwise_add(X, Y, out=Z)
id(Z) == before

True

In [63]:
before = id(X)
X += Y 
id(X) == before

True

In [64]:
import numpy as np 

P = np.ones((2, 3))
D = nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [65]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [0]:
from mxnet import autograd, nd

In [68]:
x = nd.arange(4).reshape((4, 1))
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [0]:
x.attach_grad()

In [0]:
with autograd.record():
    y = 2 * nd.dot(x.T, x)

In [0]:
y.backward()

In [0]:
y.grad

In [74]:
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [75]:
assert (x.grad - 4 * x).norm().asscalar() == 0
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [76]:
print(autograd.is_training())
with autograd.record():
    print(autograd.is_training())

False
True


In [0]:
def f(a):
    b = a * 2 
    while b.norm().asscalar() < 1000:
        b = b * 2 
    if b.sum().asscalar() > 0:
        c = b 
    else:
        c = 100 * b 
    return c 

In [79]:
help(nn.Linear)

Help on class Linear in module torch.nn.modules.linear:

class Linear(torch.nn.modules.module.Module)
 |  Applies a linear transformation to the incoming data: :math:`y = xA^T + b`
 |  
 |  Args:
 |      in_features: size of each input sample
 |      out_features: size of each output sample
 |      bias: If set to ``False``, the layer will not learn an additive bias.
 |          Default: ``True``
 |  
 |  Shape:
 |      - Input: :math:`(N, *, H_{in})` where :math:`*` means any number of
 |        additional dimensions and :math:`H_{in} = \text{in\_features}`
 |      - Output: :math:`(N, *, H_{out})` where all but the last dimension
 |        are the same shape as the input and :math:`H_{out} = \text{out\_features}`.
 |  
 |  Attributes:
 |      weight: the learnable weights of the module of shape
 |          :math:`(\text{out\_features}, \text{in\_features})`. The values are
 |          initialized from :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})`, where
 |          :math:`k = \frac{1}{\te

In [80]:
help(nd.norm)

Help on function norm:

norm(data=None, ord=_Null, axis=_Null, out_dtype=_Null, keepdims=_Null, out=None, name=None, **kwargs)
    Computes the norm on an NDArray.
    
    This operator computes the norm on an NDArray with the specified axis, depending
    on the value of the ord parameter. By default, it computes the L2 norm on the entire
    array. Currently only ord=2 supports sparse ndarrays.
    
    Examples::
    
      x = [[[1, 2],
            [3, 4]],
           [[2, 2],
            [5, 6]]]
    
      norm(x, ord=2, axis=1) = [[3.1622777 4.472136 ]
                                [5.3851647 6.3245554]]
    
      norm(x, ord=1, axis=1) = [[4., 6.],
                                [7., 8.]]
    
      rsp = x.cast_storage('row_sparse')
    
      norm(rsp) = [5.47722578]
    
      csr = x.cast_storage('csr')
    
      norm(csr) = [5.47722578]
    
    
    
    Defined in src/operator/tensor/broadcast_reduce_op_value.cc:L350
    
    Parameters
    ----------
    data : ND