<a href="https://colab.research.google.com/github/yananma/5_programs_per_day/blob/master/1106.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 4.4 自定义层

In [0]:
!pip install mxnet d2lzh

In [0]:
from mxnet import gluon, nd 
from mxnet.gluon import nn 

class CenteredLayer(nn.Block):
    def __init__(self, **kwargs):
        super(CenteredLayer, self).__init__(**kwargs)

    def forward(self, x):
        return x - x.mean()

In [3]:
layer = CenteredLayer()
layer(nd.array([1, 2, 3, 4, 5]))


[-2. -1.  0.  1.  2.]
<NDArray 5 @cpu(0)>

In [0]:
net = nn.Sequential()
net.add(nn.Dense(128), 
    CenteredLayer())

In [5]:
net.initialize()
y = net(nd.random.uniform(shape=(4, 8)))
y.mean().asscalar()

-7.212293e-10

In [6]:
params = gluon.ParameterDict()
params.get('param2', shape=(2, 3))
params

(
  Parameter param2 (shape=(2, 3), dtype=<class 'numpy.float32'>)
)

In [0]:
class MyDense(nn.Block):
    def __init__(self, units, in_units, **kwargs):
        super(MyDense, self).__init__(**kwargs)
        self.weight = self.params.get('weight', shape=(in_units, units))
        self.bias = self.params.get('bias', shape=(units, ))

    def forward(self, x):
        linear = nd.dot(x, self.weight.data()) + self.bias.data()
        return nd.relu(linear)

In [8]:
dense = MyDense(units=3, in_units=5)
dense.params 

mydense0_ (
  Parameter mydense0_weight (shape=(5, 3), dtype=<class 'numpy.float32'>)
  Parameter mydense0_bias (shape=(3,), dtype=<class 'numpy.float32'>)
)

In [9]:
dense.initialize()
dense(nd.random.uniform(shape=(2, 5)))


[[0.06917784 0.01627153 0.01029644]
 [0.02602214 0.0453731  0.        ]]
<NDArray 2x3 @cpu(0)>

In [10]:
net = nn.Sequential()
net.add(MyDense(8, in_units=64), 
    MyDense(1, in_units=8))
net.initialize()
net(nd.random.uniform(shape=(2, 64)))



[[0.03820474]
 [0.04035058]]
<NDArray 2x1 @cpu(0)>

In [0]:
from mxnet import nd 
from mxnet.gluon import nn 

x = nd.ones(3)
nd.save('x', x)

In [12]:
x2 = nd.load('x')

x2

[
 [1. 1. 1.]
 <NDArray 3 @cpu(0)>]

In [14]:
y = nd.zeros(4)
nd.save('xy', [x, y])
x2, y2 = nd.load('xy')
(x2, y2)

(
 [1. 1. 1.]
 <NDArray 3 @cpu(0)>, 
 [0. 0. 0. 0.]
 <NDArray 4 @cpu(0)>)

In [15]:
mydict = {'x': x, 'y': y}
nd.save('mydict', mydict)
mydict2 = nd.load('mydict')
mydict2

{'x': 
 [1. 1. 1.]
 <NDArray 3 @cpu(0)>, 'y': 
 [0. 0. 0. 0.]
 <NDArray 4 @cpu(0)>}

In [0]:
class MLP(nn.Block):
    def __init__(self, **kwargs):
        super(MLP, self).__init__(**kwargs)
        self.hidden = nn.Dense(256, activation='relu')
        self.output = nn.Dense(10)
    
    def forward(self, x):
        return self.output(self.hidden(x))

In [0]:
class MLP(nn.Block):
    def __init__(self, **kwargs):
        super(MLP, self).__init__(**kwargs)
        self.hidden = nn.Dense(256, activation='relu')
        self.output = nn.Dense(10)

    def forward(self, x):
        return self.output(self.hidden(x))


In [0]:
net = MLP()

net.initialize()
X = nd.random.uniform(shape=(2, 20))
Y = net(X)

In [0]:
filename = 'mlp.params'
net.save_parameters(filename)

In [0]:
net2 = MLP()
net2.load_parameters(filename)

In [64]:
Y2 = net2(X)
Y2 == Y


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
<NDArray 2x10 @cpu(0)>

## 4.6 GPU 计算

In [66]:
!nvidia-smi

Wed Nov  6 07:39:48 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   32C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [68]:
import mxnet as mx 
from mxnet import nd 
from mxnet.gluon import nn 

mx.cpu(), mx.gpu()

(cpu(0), gpu(0))

In [70]:
mx.gpu(1)

gpu(1)

In [0]:
x = nd.array([1, 2, 3])

In [72]:
x.context

cpu(0)

In [0]:
a = nd.array([1, 2, 3], ctx=mx.gpu())
a

In [0]:
B = nd.random.uniform(shape=(2, 3), ctx=mx.gpu(1))
B

In [0]:
y = x.copyto(mx.gpu())
y

In [0]:
z = x.as_in_context(mx.gpu)
z

In [0]:
y.as_in_context(mx.gpu()) is y 

In [0]:
y.copyto(mx.gpu()) is y 

In [0]:
(z + 2).exp() * y 

In [0]:
net = nn.Sequential()
net.add(nn.Dense(1))
net.initialize(ctx=mx.gpnet(yu)

In [0]:
net[0].weight.data()