<a href="https://colab.research.google.com/github/yananma/5_programs_per_day/blob/master/pytorch/ch2/2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 2.3 自动求梯度

In [4]:
import torch

x = torch.ones(2, 2, requires_grad=True)
x 

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [6]:
print(x.grad_fn)

None


In [7]:
y = x + 2 
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [8]:
y.grad_fn

In [9]:
x.is_leaf, y.is_leaf

(True, False)

In [0]:
# x.is_leaf?

# requires_grad 是 False 的时候，是 leaf。

In [13]:
z = y * y * 3 
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [14]:
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [15]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
a.requires_grad

False

In [16]:
a.requires_grad_(True)
a.requires_grad

True

In [17]:
b = (a * a).sum()
b.grad_fn

In [18]:
out.backward()
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [19]:
out2 = x.sum()
out2.backward()
x.grad

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])

In [20]:
out3 = x.sum()
x.grad.data.zero_()
out3.backward()
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [21]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x 
z = y.view(2, 2)
z

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)

In [22]:
v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)
x.grad

tensor([2.0000, 0.2000, 0.0200, 0.0020])

In [23]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2 
with torch.no_grad():
    y2 = x ** 3 
y3 = y1 + y2 

print(x, x.requires_grad)
print(y1, y1.requires_grad)
print(y2, y2.requires_grad)
print(y3, y3.requires_grad)

tensor(1., requires_grad=True) True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [24]:
y3.backward()
x.grad

tensor(2.)

In [25]:
x = torch.ones(1, requires_grad=True)
print(x.data)
print(x.data.requires_grad)

y = 2 * x 
x.data *= 100 
y.backward()
print(x)
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])
