<a href="https://colab.research.google.com/github/yananma/5_programs_per_day/blob/master/pytorch/ch2/2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 2.2 数据操作

### 2.2.1 创建 Tensor

In [0]:
# 特别注明：任何可以改变tensor内容的操作都会在方法名后加一个下划线'_'
# 例如：x.copy_(y), x.t_(), 这俩都会改变x的值。会用结果替换原来变量

In [0]:
import torch 

In [0]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
x.shape

torch.Size([12])

In [0]:
x.shape[0]

12

In [0]:
x.size()    # 和 shape 一样

torch.Size([12])

In [0]:
X = x.view(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [0]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [0]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [0]:
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [0]:
torch.randn(3, 4)    # 正态分布

tensor([[ 1.1208,  1.3648,  0.4399, -0.1687],
        [ 1.1830, -0.8392,  1.7999, -0.5877],
        [ 0.2960, -1.1753,  0.8036, -0.5075]])

### 2.2.2 运算

In [0]:
X + Y 

tensor([[ 2,  2,  6,  6],
        [ 5,  7,  9, 11],
        [12, 12, 12, 12]])

In [0]:
X * Y 

tensor([[ 0,  1,  8,  9],
        [ 4, 10, 18, 28],
        [32, 27, 20, 11]])

In [0]:
X / Y

tensor([[ 0,  1,  0,  1],
        [ 4,  2,  2,  1],
        [ 2,  3,  5, 11]])

In [0]:
torch.exp(Y.float())

tensor([[ 7.3891,  2.7183, 54.5981, 20.0855],
        [ 2.7183,  7.3891, 20.0855, 54.5981],
        [54.5981, 20.0855,  7.3891,  2.7183]])

In [0]:
torch.mm(X, Y.T)

tensor([[ 18,  20,  10],
        [ 58,  60,  50],
        [ 98, 100,  90]])

In [0]:
torch.cat((X, Y), 0)    # 0 往下放，地下室，0 楼，纵向

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])

In [0]:
torch.cat((X, Y), 1)    # 1 平着并排放，1 楼，横向

tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])

In [0]:
(X == Y)  

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [0]:
(X == Y).int()

tensor([[0, 1, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [0]:
X.sum()

tensor(66)

In [0]:
X.float().norm().item()    # norm() L2 范数，每一项平方，所有项求和，开根号；.item() 只能转换一个数。

22.494443893432617

### 2.2.3 广播机制

In [0]:
A = torch.arange(3).view(3, 1)
A

tensor([[0],
        [1],
        [2]])

In [0]:
B = torch.arange(2).view(1, 2)
B

tensor([[0, 1]])

In [0]:
A + B

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.2.4 索引

In [0]:
X[1:3]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [0]:
X[1, 2] = 9
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

In [0]:
X[1:2, :] = 12     # 第二层，所有列
X

tensor([[ 0,  1,  2,  3],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

### 2.2.5 运算的内存开销

In [0]:
before = id(Y)
Y = Y + X 
id(Y) == before 

False

In [0]:
Z = torch.zeros_like(Y)
before = id(Z)
Z[:] = X + Y
id(Z) == before 

True

In [0]:
torch.add(X, Y, out=Z)
id(Z) == before 

True

In [0]:
before = id(X)
X += Y 
id(X) == before 

True

### 2.2.6 Tensor 和 Numpy 互相转换

In [0]:
import numpy as np 

P = np.ones((2, 3))
T = torch.tensor(P)
T

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [0]:
T1 = torch.from_numpy(P)    # 从后往前念，P from numpy，转化为 torch 的 Tensor
T1

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [0]:
T.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]])